---
driver:
  name: ec2
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_ssh_key_id: <%= ENV["AWS_KEYPAIR_NAME"] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: amazon-2014.03.1
  driver:
    image_id: ami-ed8e9284
    username: ec2-user
    ssh_key: <%= ENV["EC2_SSH_KEY_PATH"] %>
  run_list:
  - recipe[sudo]
  attributes:
    riak:
      package:
        checksum:
          amazon:
            "2014": "2cf9f2481409d2871a6d453a9287f317bd4f5c1cb2e49432f4fee0ac106af56c"

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: 1
          minor: 4
          incremental: 8
- name: enterprise
  run_list:
  - recipe[minitest-handler]
  - recipe[riak]
  attributes:
    riak:
      package:
        version:
          major: 1
          minor: 4
          incremental: 8
        enterprise_key: <%= (ENV["RIAK_ENTERPRISE_KEY"].nil? ? "" : ENV["RIAK_ENTERPRISE_KEY"]) %>
